CXX := g++ -std=c++11
CC  := gcc

CFLAGS := -g -DBAGHEERA2 -DLIBSYS_API_EXTENSION -I.
LDFLAGS := -lpthread -lrt -lsys_obd -ljansson -liniparser -lcrypto -lssl

ND_CORE_LIB_ROOT ?= /usr/local

LDFLAGS += -L$(ND_CORE_LIB_ROOT)/nd_thirdparty_lib/lib/kvs_sdk/bagheera2/lib
_INCLUDES += -I$(ND_CORE_LIB_ROOT)/cpp/inc/ndmb -I$(ND_CORE_LIB_ROOT)/cpp/inc/bagheera2
